name: Compilation Errors
description: File an issue you encountered while coding that produced a compilation error you did not understand
title: "[Compilation Error]: "
labels: ["compilation-errors"]

assignees:
 - davispolito
body:
 - type: markdown
   attributes:
    value: |
     Thanks for taking the time to fill out this bug report!

 - type: textarea
   id: what-happened
   attributes:
    label: What happened?
    description: Briefly describe what you were trying to do
    placeholder: Tell us what you see!
    value: "CMake broke"
   validations:
    required: true

 - type: textarea
   id: steps-to-reproduce
   attributes:
    label: Tell us how to reproduce this behavior!
    placeholder: write code
    value: "added new folder and other files can't find it"

 - type: textarea
   id: commit
   attributes:
    label: Commit
    description: link to the commit where this breaking change occurs. Please push them to their own branch i.e. compilation-errors/myerror
    value: "c12345"
   validations:
    required: true
 - type: textarea
   id: logs
   attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
